
var map_data = {
};

var MAP_BASE_TEMPLATE = {
	grid_width: 32, 
	grid_height: 32, 
};

var map = {
};

function map_init()
{
	for (var id in map_data)
	{
		map[id] = Map(map_data[id]);
	}
}

map_data[MAP_OUTSIDE_TOWER = 0] = extend(MAP_BASE_TEMPLATE, {
	width: 16, 
	height: 16, 
});

map_data[MAP_OUTSIDE_TOWER = 0].grid = [
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT_GRASS, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT_GRASS, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT_GRASS, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT_GRASS, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT_GRASS, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT_GRASS, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT_GRASS, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT_GRASS, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
	[TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
		TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, TILE_BROWN_DIRT, 
	], 
];